inherits: ..\\languages-index.yml

dimensions:  
- alias:  operation
  values: [index] 

- alias: product
  values: [python-net]

dictionaries: [ ..\\..\\data\\products.json ]

outputPath: "search\\{product}\\_index.{lang}.md"
