inherits: ..\\languages-formats.yml

dimensions:
- alias: product
  values: [java]
- alias:  operation
  values: [boolean]
- alias:  fileformat
  values: [ docx, pdf, pptx, txt, xlsx ]

generationRules:
  include:
  - fileformat[docx, pdf, pptx, txt, xlsx]
  
outputPath: "search\\{product}\\{operation}\\{fileformat}.{lang}.md"

dictionaries: [ ..\\..\\data\\products.json ]
